version: '3.3'

services:
  app:
    build: .
    container_name: coffee_shop_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

